<?php

/**
 * PlugincomponentSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugincomponentSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugincomponentSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugincomponentSlot');
    }
}